version: 2
updates:
  # Maintain dependencies in the root CLI package
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies in the TypeScript base template
  - package-ecosystem: "npm"
    directory: "/template/base/ts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies in the JavaScript base template
  - package-ecosystem: "npm"
    directory: "/template/base/js"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
